name: 'Verificação básica de código'

on:
  push:
    branches:
      - 'main'

jobs:
  basic-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Subir o Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'

      - name: Instalar as dependências
        run: npm install
        working-directory: ./backend

      - name: Rodar o ESLint
        run: npm run lint
        working-directory: ./backend

      - name: Rodar os testes unitários com 80% de cobertura de código
        run: npm run test:cov
        working-directory: ./backend
